/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cybercafeadmin;

import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class StartSession extends java.awt.Frame {

    /**
     * Creates new form StartSession
     */
    public StartSession() {
        initComponents();
        DatabaseHandler.getAllAvailableIds().forEach((t) -> idList.add(t));
        idList.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                HashMap<String, String> info = DatabaseHandler.getInfo(idList.getSelectedItem());
                name.setText(info.get("name"));
                email.setText(info.get("email"));
            }
        });
        start.addActionListener((ActionEvent e) -> {
            String pc = DatabaseHandler.initSession(idList.getSelectedItem());
            int input;
            if(!(pc == null)){
                input = JOptionPane.showOptionDialog(null, "Session started! Allotted PC:" + pc , "Success!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);  
                if(input == JOptionPane.OK_OPTION) {
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(new JFrame(),"All PCs are already allotted!", "Alert", JOptionPane.WARNING_MESSAGE);
            }
        });
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        idList = new java.awt.List();
        label2 = new java.awt.Label();
        name = new java.awt.TextField();
        label3 = new java.awt.Label();
        email = new java.awt.TextField();
        start = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label1.setText("Select ID:");
        jPanel1.add(label1);
        jPanel1.add(idList);

        label2.setText("Name");
        jPanel1.add(label2);

        name.setEditable(false);
        name.setText("Name");
        jPanel1.add(name);

        label3.setText("Email");
        jPanel1.add(label3);

        email.setEditable(false);
        email.setText("Email");
        jPanel1.add(email);

        start.setText("Start");
        jPanel1.add(start);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField email;
    private java.awt.List idList;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField name;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
