/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cybercafeadmin;

import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

public class TerminateSession extends java.awt.Frame {

    /**
     * Creates new form TerminateSession
     */
    public TerminateSession() {
        initComponents();
        DatabaseHandler.getAllCurrentUserIds().forEach((e) -> idList.add(e));
        idList.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                HashMap<String, String> info = DatabaseHandler.getInfo(idList.getSelectedItem());
                name.setText(info.get("name"));
                email.setText(info.get("email"));
            }
        });
        end.addActionListener((ActionEvent e) -> {
            int response = JOptionPane.showConfirmDialog(null, "Are you sure want to finish session ?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.NO_OPTION) {
              
            } else if (response == JOptionPane.YES_OPTION) {
                int bill;
                ArrayList<String> info = DatabaseHandler.terminateSession(idList.getSelectedItem());
                int input = JOptionPane.showOptionDialog(null, "Session finished! In time:" + info.get(0).substring(0, info.get(0).indexOf(".")), "Success!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);  
                if(input == JOptionPane.OK_OPTION) {
                    try{
                        bill = Integer.parseInt(JOptionPane.showInputDialog("Enter bill amount: "));
                    } catch(NumberFormatException ye){
                        ye.printStackTrace();
                        bill = 50;
                    }
                    DatabaseHandler.setBill(info.get(1), bill);
                }
                dispose();
            } else if (response == JOptionPane.CLOSED_OPTION) {
              
            }
        });
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        idList = new java.awt.List();
        label2 = new java.awt.Label();
        name = new java.awt.TextField();
        label3 = new java.awt.Label();
        email = new java.awt.TextField();
        end = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label1.setText("Select ID:");
        jPanel1.add(label1);
        jPanel1.add(idList);

        label2.setText("Name:");
        jPanel1.add(label2);

        name.setText("Name");
        jPanel1.add(name);

        label3.setText("Email:");
        jPanel1.add(label3);

        email.setText("Email");
        jPanel1.add(email);

        end.setText("Finish");
        end.setActionCommand("Finish");
        jPanel1.add(end);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField email;
    private javax.swing.JButton end;
    private java.awt.List idList;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField name;
    // End of variables declaration//GEN-END:variables
}
