package cybercafeadmin;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class UpdateUser extends java.awt.Frame {

    public UpdateUser() {
        initComponents();
        ArrayList<String> ids = DatabaseHandler.getAllIds();
        ids.forEach((i) -> {
            idList.add(i);
        });
        idList.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                HashMap<String, String> info = DatabaseHandler.getInfo(idList.getSelectedItem());
                name.setText(info.get("name"));
                email.setText(info.get("email"));
                phone.setText(info.get("phone"));
                address.setText(info.get("address"));
            }
        });
        update.addActionListener((e) -> {
            HashMap<String, String> info = new HashMap<>();
            if(email.getText().trim().isEmpty() || name.getText().trim().isEmpty() || phone.getText().trim().isEmpty() || address.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(new JFrame(),"Add proper credentials!", "Alert", JOptionPane.WARNING_MESSAGE); 
                return;
            }
            info.put("name", name.getText().trim());
            info.put("email", email.getText().trim());
            info.put("phone", phone.getText().trim());
            info.put("address", address.getText().trim());
            info.put("id", idList.getSelectedItem());
            if(DatabaseHandler.updateInfo(info)){
                int input = JOptionPane.showOptionDialog(null, "Update Successful!", "Success!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                if(input == JOptionPane.OK_OPTION) {
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(new JFrame(),"Update Unsuccessful! Something went wrong.", "Alert", JOptionPane.WARNING_MESSAGE);
            }
        });
        setVisible(true);
        setTitle("UPDATE USER");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        idList = new java.awt.List();
        label1 = new java.awt.Label();
        name = new java.awt.TextField();
        label2 = new java.awt.Label();
        email = new java.awt.TextField();
        label3 = new java.awt.Label();
        phone = new java.awt.TextField();
        label4 = new java.awt.Label();
        address = new java.awt.TextField();
        update = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jToggleButton1.setText("jToggleButton1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label5.setText("Select ID:");
        jPanel1.add(label5);

        idList.setName("idList"); // NOI18N
        jPanel1.add(idList);
        idList.getAccessibleContext().setAccessibleName("idList");

        label1.setText("Name");
        jPanel1.add(label1);
        label1.getAccessibleContext().setAccessibleName("");

        name.setText("Name ");
        jPanel1.add(name);

        label2.setText("Email");
        jPanel1.add(label2);

        email.setText("Email");
        jPanel1.add(email);

        label3.setText("Phone");
        jPanel1.add(label3);

        phone.setColumns(10);
        phone.setText("Phone");
        jPanel1.add(phone);

        label4.setText("Address");
        jPanel1.add(label4);

        address.setText("Address");
        jPanel1.add(address);

        update.setText("Update");
        jPanel1.add(update);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField address;
    private java.awt.TextField email;
    private java.awt.List idList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField name;
    private java.awt.TextField phone;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
